Me acorde de una idea que tenia hace mucho tiempo, no necesariamente para ganar plata :P. Una era hacer una especie de HandmadeHero pero en espanol. Otra idea era hacer entrevista tecnicas a programadores latinoamericanos. Generalmente siempre veo charlas de 10 - 15 min donde desarrolladores solo tocan la superficie de temas potencialmente super interesantes. Seria entretenido ver conversaciones de +45 minutos con programadores experimentados. Se por experiencia propia que en Chile hay personas mega cabronas que generalmente son low profile y que tienen puntos de vista o conocimientos que podrian beneficiar al resto.